import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Vercel Workflow DevKit; ships its own `/* eslint-disable */`.
    "src/app/.well-known/**",
  ]),
  {
    // Honor the `_`-prefix convention the codebase already uses to mark a
    // binding as intentionally unused (e.g. `_node`, `_stripped`, `catch (_e)`).
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  {
    // Playwright fixtures destructure a `use` callback (`await use(page)`),
    // which the React Hooks plugin mistakes for the `use` hook. These files
    // are test infrastructure, not React components.
    files: ["e2e/**"],
    rules: {
      "react-hooks/rules-of-hooks": "off",
    },
  },
]);

export default eslintConfig;
