import { zodSchema } from "ai";
import { z } from "zod";
import type { DefinitionKind } from "@/db/schema";
import {
  createBranch,
  deleteFile,
  createPullRequest,
  getGiteaPRUrl,
} from "@/lib/gitea-client";
import {
  getDefinitionByName,
  markDefinitionPendingDeletion,
} from "@/lib/actions/definitions";

const DELETABLE_KINDS = [
  "dimension",
  "logger_table",
  "lattik_table",
  "metric",
] as const satisfies readonly DefinitionKind[];
type DeletableKind = (typeof DELETABLE_KINDS)[number];

const KIND_DIRS: Record<DeletableKind, string> = {
  dimension: "dimensions",
  logger_table: "logger_tables",
  lattik_table: "lattik_tables",
  metric: "metrics",
};

// Mirrors the guard in submit-pr.ts: values flowing into branch names,
// commit messages, and PR titles must be tightly constrained, since the
// LLM controls this input. A prompt-injected name like `../../evil` or one
// with embedded newlines would otherwise corrupt the branch path or trick
// a reviewer reading the commit log.
const SAFE_NAME_RE = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)?$/;
const MAX_NAME_LENGTH = 60;

function isSafeDefinitionName(name: string): boolean {
  return (
    name.length > 0 &&
    name.length <= MAX_NAME_LENGTH &&
    SAFE_NAME_RE.test(name)
  );
}

async function resolveKind(
  name: string,
  hint: DeletableKind | undefined
): Promise<{ kind: DeletableKind; id: string } | { error: string }> {
  if (hint) {
    const def = await getDefinitionByName(hint, name);
    if (!def) return { error: `No ${hint} named '${name}' was found.` };
    return { kind: hint, id: def.id };
  }
  const matches: Array<{ kind: DeletableKind; id: string }> = [];
  for (const k of DELETABLE_KINDS) {
    const def = await getDefinitionByName(k, name);
    if (def) matches.push({ kind: k, id: def.id });
  }
  if (matches.length === 0) {
    return { error: `No deletable definition named '${name}' was found.` };
  }
  if (matches.length > 1) {
    return {
      error: `Multiple definitions match '${name}' (${matches
        .map((m) => m.kind)
        .join(", ")}). Re-call deleteDefinition with an explicit kind to disambiguate.`,
    };
  }
  return matches[0];
}

export const deleteDefinitionTool = {
  description:
    "Create a PR that deletes the YAML file for a dimension, logger table, lattik table, or metric from the pipelines repo. Takes the definition's name and optionally its kind — if the name is unique across kinds, kind may be omitted. The returned `prUrl` is a clickable URL that MUST be shared with the user verbatim.",
  inputSchema: zodSchema(
    z.object({
      name: z
        .string()
        .describe(
          "The snake_case name of the definition to delete. For logger tables, use the qualified `schema.table_name` form."
        ),
      kind: z
        .enum(DELETABLE_KINDS)
        .optional()
        .describe(
          "Kind of definition. Required only when the name is ambiguous across kinds."
        ),
    })
  ),
  execute: async (input: { name: string; kind?: DeletableKind }) => {
    if (!isSafeDefinitionName(input.name)) {
      return {
        status: "error",
        message: `Definition name '${input.name}' is not safe to submit. Names must be snake_case (optionally schema.table_name) and at most ${MAX_NAME_LENGTH} characters.`,
      };
    }
    const resolved = await resolveKind(input.name, input.kind);
    if ("error" in resolved) {
      return { status: "error", message: resolved.error };
    }
    const { kind, id: definitionId } = resolved;
    const path = `definitions/${KIND_DIRS[kind]}/${input.name}.yaml`;

    // Logger-table qualified names contain a dot that's not valid in git refs.
    const safeBranchName = input.name.replace(/\./g, "_");
    const branchName = `delete/${kind}/${safeBranchName}-${Date.now()}`;
    const message = `Delete ${kind}: ${input.name}`;

    try {
      await createBranch(branchName);
      await deleteFile(branchName, path, message);
      const pr = await createPullRequest(
        message,
        `## Deletion\n\n**Kind:** ${kind}\n**Name:** ${input.name}\n**File:** \`${path}\`\n\nGenerated by Lattik Studio Data Architect.`,
        branchName
      );
      const prUrl = getGiteaPRUrl(pr.number);

      // Flip the DB row so the Gitea webhook knows to delete it when this PR
      // merges. Without this, the handler would only find rows by the
      // original creation PR's URL and leave the row stale indefinitely.
      await markDefinitionPendingDeletion(definitionId, prUrl);

      return {
        status: "submitted",
        prNumber: pr.number,
        prUrl,
        branch: branchName,
        file: path,
        kind,
        name: input.name,
      };
    } catch (error) {
      console.error("deleteDefinition error:", error);
      const detail = error instanceof Error ? error.message : String(error);
      return {
        status: "error",
        message: `Failed to create deletion PR: ${detail}`,
      };
    }
  },
};
