import { zodSchema } from "ai";
import { z } from "zod";
import type { DefinitionKind } from "@/db/schema";
import {
  createBranch,
  commitFiles,
  createPullRequest,
  getGiteaPRUrl,
} from "@/lib/gitea-client";
import { updateDefinition, getDefinitionByName } from "@/lib/actions/definitions";
import { generateYamlFiles } from "../yaml-generator";

export const submitPRTool = {
  description:
    "Generate YAML files from a definition and submit a PR to Gitea for review. The definition must have been saved with updateDefinition first.",
  inputSchema: zodSchema(
    z.object({
      kind: z
        .enum(["entity", "dimension", "logger_table", "lattik_table", "metric"])
        .describe("The type of definition"),
      name: z.string().describe("The name of the definition"),
      specJson: z
        .string()
        .describe("JSON string of the definition spec"),
    })
  ),
  execute: async (input: {
    kind: DefinitionKind;
    name: string;
    specJson: string;
  }) => {
    let spec: unknown;
    try {
      spec = JSON.parse(input.specJson);
    } catch {
      return { status: "error", message: "Invalid JSON in specJson" };
    }

    const branchName = `define/${input.kind}/${input.name}-${Date.now()}`;

    try {
      // Generate YAML files
      const files = generateYamlFiles(input.kind, input.name, spec);

      // Create branch
      await createBranch(branchName);

      // Commit files
      await commitFiles(
        branchName,
        files,
        `Add ${input.kind}: ${input.name}`
      );

      // Create PR
      const pr = await createPullRequest(
        `Define ${input.kind}: ${input.name}`,
        `## Definition\n\n**Kind:** ${input.kind}\n**Name:** ${input.name}\n\nGenerated by Lattik Studio Data Architect.`,
        branchName
      );

      const prUrl = getGiteaPRUrl(pr.number);

      // Update definition status in DB
      const def = await getDefinitionByName(input.kind, input.name);
      if (def) {
        await updateDefinition(def.id, {
          status: "pending_review",
          prUrl,
        });
      }

      return {
        status: "submitted",
        prNumber: pr.number,
        prUrl,
        branch: branchName,
        files: files.map((f) => f.path),
      };
    } catch (error) {
      console.error("submitPR error:", error);
      return {
        status: "error",
        message: "Failed to submit PR. Please check Gitea is running and try again.",
      };
    }
  },
};
