import { zodSchema } from "ai";
import { z } from "zod";
import type { DefinitionKind } from "@/db/schema";
import {
  createBranch,
  commitFiles,
  createPullRequest,
  getGiteaPRUrl,
} from "@/lib/gitea-client";
import { updateDefinition, getDefinitionByName } from "@/lib/actions/definitions";
import { getCanvasFormState } from "../canvas-to-spec";

interface YamlFile {
  path: string;
  content: string;
}

function readYamlFilesFromCanvas(canvasState: unknown): YamlFile[] | null {
  const state = getCanvasFormState(canvasState);
  const raw = state.files;
  if (!Array.isArray(raw)) return null;
  const files: YamlFile[] = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const path = (item as { path?: unknown }).path;
    const content = (item as { content?: unknown }).content;
    if (typeof path === "string" && path.length > 0 && typeof content === "string") {
      files.push({ path, content });
    }
  }
  return files.length > 0 ? files : null;
}

export function createSubmitPRTool(getCanvasState: () => unknown) {
  return {
    description:
      "Submit the YAML files currently displayed in the canvas YAML editor as a PR to Gitea for review. Requires that generateYaml has been called first — reads the (possibly user-edited) YAML files directly from canvas state. The returned `prUrl` is a clickable URL that MUST be shared with the user verbatim.",
    inputSchema: zodSchema(
      z.object({
        kind: z
          .enum(["entity", "dimension", "logger_table", "lattik_table", "metric"])
          .describe("The type of definition currently on the canvas"),
      })
    ),
    execute: async (input: { kind: DefinitionKind }) => {
      const canvasState = getCanvasState();
      const state = getCanvasFormState(canvasState);
      const name = typeof state.name === "string" && state.name.length > 0 ? state.name : null;
      if (!name) {
        return {
          status: "error",
          message:
            "Canvas has no definition name. Run generateYaml first so the YAML editor is populated.",
        };
      }

      const files = readYamlFilesFromCanvas(canvasState);
      if (!files) {
        return {
          status: "error",
          message:
            "No YAML files found on the canvas. Run generateYaml first to populate the YAML editor before submitting a PR.",
        };
      }

      const branchName = `define/${input.kind}/${name}-${Date.now()}`;

      try {
        // Create branch
        await createBranch(branchName);

        // Commit files
        await commitFiles(
          branchName,
          files,
          `Add ${input.kind}: ${name}`
        );

        // Create PR
        const pr = await createPullRequest(
          `Define ${input.kind}: ${name}`,
          `## Definition\n\n**Kind:** ${input.kind}\n**Name:** ${name}\n\nGenerated by Lattik Studio Data Architect.`,
          branchName
        );

        const prUrl = getGiteaPRUrl(pr.number);

        // Update definition status in DB
        const def = await getDefinitionByName(input.kind, name);
        if (def) {
          await updateDefinition(def.id, {
            status: "pending_review",
            prUrl,
          });
        }

        return {
          status: "submitted",
          prNumber: pr.number,
          prUrl,
          branch: branchName,
          files: files.map((f) => f.path),
        };
      } catch (error) {
        console.error("submitPR error:", error);
        return {
          status: "error",
          message: "Failed to submit PR. Please check Gitea is running and try again.",
        };
      }
    },
  };
}
