import { fromBinary } from "@bufbuild/protobuf";
import { describe, expect, it, vi } from "vitest";
import {
  ConsoleTransport,
  createLoggerClient,
  EnvelopeSchema,
  type Transport,
} from "../src/index.js";
import { EnvelopeSchema as DirectEnvelopeSchema } from "../src/gen/lattik/logger/v1/envelope_pb.js";

/** Collect raw bytes sent through the transport. */
const collect = (): { calls: Uint8Array[]; transport: Transport } => {
  const calls: Uint8Array[] = [];
  return {
    calls,
    transport: { send: async (data) => { calls.push(data); } },
  };
};

/**
 * Minimal inline proto schema for testing.
 * In real usage this would be generated by buf from a .proto file.
 * We reuse the Envelope schema itself as a stand-in payload
 * just to verify the serialization round-trip works.
 */

describe("createLoggerClient", () => {
  it("sends a protobuf-encoded Envelope with payload bytes", async () => {
    const { calls, transport } = collect();

    // Use the Envelope schema as a stand-in payload for testing
    const logger = createLoggerClient({
      table: "ingest.click_events",
      schema: DirectEnvelopeSchema,
      transport,
    });

    await logger.log({ table: "nested", eventId: "inner", eventTimestamp: "t", payload: new Uint8Array() });

    expect(calls).toHaveLength(1);

    // Decode the outer envelope
    const envelope = fromBinary(EnvelopeSchema, calls[0]!);
    expect(envelope.table).toBe("ingest.click_events");
    expect(envelope.eventId).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
    );
    expect(envelope.eventTimestamp).toBeTruthy();
    expect(envelope.payload.length).toBeGreaterThan(0);
  });
});

describe("ConsoleTransport", () => {
  it("decodes the envelope and logs JSON to stdout", async () => {
    const spy = vi.spyOn(console, "log").mockImplementation(() => {});
    const consoleCalls: Uint8Array[] = [];
    const consoleTransport = new ConsoleTransport();

    // Build an envelope through the client
    const logger = createLoggerClient({
      table: "ingest.test_events",
      schema: DirectEnvelopeSchema,
      transport: consoleTransport,
    });

    await logger.log({ table: "x", eventId: "y", eventTimestamp: "z", payload: new Uint8Array() });

    expect(spy).toHaveBeenCalledOnce();
    const logged = JSON.parse(spy.mock.calls[0]![0] as string);
    expect(logged.table).toBe("ingest.test_events");
    expect(logged.eventId).toBeTruthy();
    expect(logged.eventTimestamp).toBeTruthy();
    expect(typeof logged.payloadBytes).toBe("number");

    spy.mockRestore();
  });
});
