import type { DefinitionKind } from "@/db/schema";
import { toYaml } from "@/lib/yaml";

const KIND_DIRS: Record<DefinitionKind, string> = {
  entity: "entities",
  dimension: "dimensions",
  logger_table: "logger_tables",
  lattik_table: "lattik_tables",
  metric: "metrics",
};

export function generateYamlFiles(
  kind: DefinitionKind,
  name: string,
  spec: unknown
): { path: string; content: string }[] {
  const dir = KIND_DIRS[kind];
  const header = `# ${kind}: ${name}\n# Generated by Lattik Studio Data Architect\n\n`;
  const yamlContent = header + toYaml(spec);

  return [
    {
      path: `definitions/${dir}/${name}.yaml`,
      content: yamlContent,
    },
  ];
}
