/**
 * Generates Airflow DAG YAML specs from merged definitions and uploads them
 * to S3 (MinIO).  The Python DAG renderer in Airflow reads these YAML files
 * and dynamically creates DAG objects.
 */

import { eq } from "drizzle-orm";
import { getDb } from "@/db";
import * as schema from "@/db/schema";
import { toYaml } from "./yaml";
import { putObject, listObjects, deleteObject } from "./s3-client";

const S3_BUCKET = process.env.S3_DAG_BUCKET ?? "warehouse";
const S3_DAG_PREFIX = process.env.S3_DAG_PREFIX ?? "airflow-dags/";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface TaskSpec {
  task_id: string;
  operator: "wait" | "spark";
  config: Record<string, string>;
  dependencies: string[];
}

interface DagSpec {
  dag_id: string;
  description: string;
  schedule: string | null;
  tags: string[];
  default_args: {
    owner: string;
    retries: number;
    retry_delay_minutes: number;
  };
  tasks: TaskSpec[];
}

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

function dagSpecForLattikTable(
  tableName: string,
  tableSpec: Record<string, unknown>,
): DagSpec {
  const tasks: TaskSpec[] = [];

  // Wait tasks — one per unique source table across column families
  const columnFamilies =
    (tableSpec.column_families as Array<{ source: string; name: string }>) ?? [];
  const sourceTables = [...new Set(columnFamilies.map((f) => f.source))];

  for (const sourceTable of sourceTables) {
    tasks.push({
      task_id: `wait__${sourceTable.replace(".", "_")}`,
      operator: "wait",
      config: { table: sourceTable },
      dependencies: [],
    });
  }

  // Build task — depends on all wait tasks
  tasks.push({
    task_id: `build__${tableName}`,
    operator: "spark",
    config: {
      job_type: "lattik_table",
      job_name: tableName,
      spec_json: JSON.stringify(tableSpec),
    },
    dependencies: tasks
      .filter((t) => t.operator === "wait")
      .map((t) => t.task_id),
  });

  return {
    dag_id: `lattik__${tableName}`,
    description:
      (tableSpec.description as string) ?? `Build ${tableName} lattik table`,
    schedule: null,
    tags: ["lattik", "lattik_table"],
    default_args: {
      owner: "lattik",
      retries: 2,
      retry_delay_minutes: 5,
    },
    tasks,
  };
}

/**
 * Generate DAG YAML files from all merged lattik_table definitions and
 * upload them to S3.  Returns the list of S3 keys that were written.
 */
export async function generateDags(): Promise<string[]> {
  const db = getDb();

  const mergedDefs = await db
    .select()
    .from(schema.definitions)
    .where(eq(schema.definitions.status, "merged"));

  const lattikTables = mergedDefs.filter((d) => d.kind === "lattik_table");

  const writtenKeys: string[] = [];

  for (const table of lattikTables) {
    const spec = table.spec as Record<string, unknown>;
    const tableName = (spec.name as string) ?? table.name;
    const dagSpec = dagSpecForLattikTable(tableName, spec);

    const header =
      `# DAG: ${dagSpec.dag_id}\n` +
      `# Generated by Lattik Studio from merged definition "${tableName}"\n\n`;
    const yamlContent = header + toYaml(dagSpec);
    const key = `${S3_DAG_PREFIX}${dagSpec.dag_id}.yaml`;

    await putObject(S3_BUCKET, key, yamlContent);
    writtenKeys.push(key);
  }

  // Clean up S3 keys for DAGs whose definitions were removed
  const expectedKeys = new Set(writtenKeys);
  const existingKeys = await listObjects(S3_BUCKET, S3_DAG_PREFIX);
  for (const existing of existingKeys) {
    if (existing.endsWith(".yaml") && !expectedKeys.has(existing)) {
      await deleteObject(S3_BUCKET, existing);
    }
  }

  return writtenKeys;
}
