import type { LoggerTable } from "@/extensions/data-architect/schema";
import { firehoseS3Prefix, firehoseStreamName } from "@/lib/firehose";

/**
 * Pure renderer for a Logger Table's npm package. Given a table spec and a
 * target version, it produces the in-memory file set of a publishable,
 * self-contained npm package (`@<scope>/logger-<table>`) for that table's
 * Firehose stream.
 *
 * We emit JavaScript + `.d.ts` directly (no `tsc` build step) — the runtime is
 * tiny (a typed event interface plus a class wrapping `PutRecordBatchCommand`),
 * so hand-emitting both keeps the publish step a lightweight, deterministic,
 * I/O-free function. The actual packing + publish lives in
 * `@/lib/github-packages`; this module stays pure so it's trivially testable.
 */

/** lattik-expression column types → TypeScript types for the event interface. */
function tsTypeFor(columnType: string): string {
  switch (columnType) {
    case "string":
    case "timestamp": // ISO 8601 string
    case "date": // YYYY-MM-DD string
      return "string";
    case "int32":
    case "int64":
    case "float":
    case "double":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    default:
      return "unknown";
  }
}

/**
 * Turn a logger table name like "events.click_events" into PascalCase
 * identifiers usable in TS — "EventsClickEvents".
 */
function pascalCase(name: string): string {
  return name
    .split(/[.\-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

/**
 * Map a logger table name to its scoped npm package name, e.g.
 * ("ingest.impressions", "@eloquio") → "@eloquio/logger-ingest-impressions".
 * The unscoped part is restricted to npm-safe `[a-z0-9-]` (dots and
 * underscores in the table name become hyphens).
 */
export function packageNameFor(tableName: string, scope: string): string {
  const slug = tableName
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `${scope}/logger-${slug}`;
}

/** A single column's identity for diffing — name + type + sensitivity. */
export interface ColumnSig {
  name: string;
  type: string;
  /**
   * Stable, sorted CSV of the column's set sensitivity flags
   * (e.g. "financial,pii"), omitted when the column has no classification.
   * Part of the signature so a compliance reclassification bumps the version
   * instead of being silently treated as "unchanged".
   */
  classification?: string;
}

/** Stable CSV of a column's set classification flags, or undefined if none. */
function classificationSig(c: LoggerTable["columns"][number]): string | undefined {
  if (!c.classification) return undefined;
  const flags = Object.entries(c.classification)
    .filter(([, v]) => v)
    .map(([k]) => k)
    .sort();
  return flags.length ? flags.join(",") : undefined;
}

/**
 * Normalized, order-independent signature of a table's columns. Embedded in
 * the published `package.json` (as `lattikSchema`) so the next publish can
 * diff against the last-published schema to derive the semver bump. Sorted by
 * name so column reordering alone never looks like a change.
 */
export function schemaSignature(table: LoggerTable): ColumnSig[] {
  return table.columns
    .map((c) => {
      const cls = classificationSig(c);
      const sig: ColumnSig = { name: c.name, type: c.type };
      if (cls) sig.classification = cls;
      return sig;
    })
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
}

/** One file in the generated package, `path` relative to the package root. */
export interface PackageFile {
  path: string;
  content: string;
}

export interface RenderOptions {
  /** semver for this package.json. */
  version: string;
  /** npm scope, including the leading "@" (e.g. "@eloquio"). */
  scope: string;
  /** Value for the package.json `repository` field. */
  repositoryUrl?: string;
}

const DEFAULT_REPOSITORY_URL = "https://github.com/Eloquio/lattik-studio";
const GH_PACKAGES_REGISTRY = "https://npm.pkg.github.com";

/** Render the `<Name>Event` interface body (shared doc-comment formatting). */
function renderInterfaceBody(table: LoggerTable): string {
  return table.columns
    .map((c) => {
      const docLines: string[] = [];
      if (c.description) docLines.push(c.description);
      if (c.tags?.length) docLines.push(`tags: ${c.tags.join(", ")}`);
      const doc =
        docLines.length > 0 ? `  /** ${docLines.join(" — ")} */\n` : "";
      return `${doc}  ${c.name}: ${tsTypeFor(c.type)};`;
    })
    .join("\n");
}

function renderDts(
  ifaceName: string,
  className: string,
  table: LoggerTable,
): string {
  return `// Generated by Lattik Studio — do not edit by hand.
import type {
  FirehoseClient,
  PutRecordBatchCommandOutput,
} from "@aws-sdk/client-firehose";

export interface ${ifaceName} {
${renderInterfaceBody(table)}
}

export declare const STREAM_NAME: string;

export declare class ${className} {
  constructor(client: FirehoseClient);
  /**
   * Send a batch of events. Firehose accepts up to 500 records or 4 MiB per
   * call; this method does NOT chunk — callers with larger batches should
   * split first. Returns the raw SDK response so callers can inspect
   * \`FailedPutCount\` and retry partial failures.
   */
  send(events: ${ifaceName}[]): Promise<PutRecordBatchCommandOutput>;
}
`;
}

function renderJs(className: string, streamName: string): string {
  return `// Generated by Lattik Studio — do not edit by hand.
import { PutRecordBatchCommand } from "@aws-sdk/client-firehose";

export const STREAM_NAME = ${JSON.stringify(streamName)};

export class ${className} {
  constructor(client) {
    this.client = client;
  }

  async send(events) {
    const encoder = new TextEncoder();
    const records = events.map((event) => ({
      Data: encoder.encode(JSON.stringify(event) + "\\n"),
    }));
    return this.client.send(
      new PutRecordBatchCommand({
        DeliveryStreamName: STREAM_NAME,
        Records: records,
      }),
    );
  }
}
`;
}

function renderReadme(
  table: LoggerTable,
  packageName: string,
  className: string,
  streamName: string,
): string {
  const s3Prefix = firehoseS3Prefix(table.name);
  return `# ${packageName}

Typed Firehose logger client for the **\`${table.name}\`** Logger Table.

> Generated by Lattik Studio — do not edit by hand. A new version is published
> automatically whenever the table's definition changes.

- **Firehose stream:** \`${streamName}\`
- **S3 output:** \`s3://<bucket>/${s3Prefix}\`

## Install

This package is published to GitHub Packages under the \`@eloquio\` scope. Add
an \`.npmrc\` to your project:

\`\`\`
@eloquio:registry=${GH_PACKAGES_REGISTRY}
//npm.pkg.github.com/:_authToken=\${GITHUB_TOKEN}
\`\`\`

(In CI the built-in \`GITHUB_TOKEN\` works for internal packages within the org;
locally use a personal access token with \`read:packages\`.)

\`\`\`sh
pnpm add ${packageName} @aws-sdk/client-firehose
\`\`\`

\`@aws-sdk/client-firehose\` is a peer dependency.

## Usage

\`\`\`ts
import { FirehoseClient } from "@aws-sdk/client-firehose";
import { ${className} } from "${packageName}";

const logger = new ${className}(new FirehoseClient({ region: "us-east-1" }));
await logger.send([{ /* typed event */ }]);
\`\`\`

The AWS client must have credentials with \`firehose:PutRecordBatch\` on the
\`${streamName}\` stream.
`;
}

/**
 * Render the full package file set for a logger table at the given version.
 * Pure — returns in-memory files; the caller packs + publishes them.
 */
export function renderLoggerPackage(
  table: LoggerTable,
  opts: RenderOptions,
): PackageFile[] {
  const ifaceName = `${pascalCase(table.name)}Event`;
  const className = `${pascalCase(table.name)}Logger`;
  const streamName = firehoseStreamName(table.name);
  const packageName = packageNameFor(table.name, opts.scope);

  const pkg = {
    name: packageName,
    version: opts.version,
    description: `Typed Firehose logger client for the "${table.name}" Logger Table. Generated by Lattik Studio.`,
    type: "module",
    main: "./index.js",
    types: "./index.d.ts",
    exports: {
      ".": { types: "./index.d.ts", import: "./index.js" },
    },
    files: ["index.js", "index.d.ts", "README.md"],
    publishConfig: { registry: GH_PACKAGES_REGISTRY },
    repository: opts.repositoryUrl ?? DEFAULT_REPOSITORY_URL,
    peerDependencies: { "@aws-sdk/client-firehose": "^3" },
    // Embedded column signature — diffed by the next publish to derive the
    // semver bump. Not read at runtime.
    lattikSchema: schemaSignature(table),
  };

  return [
    { path: "package.json", content: JSON.stringify(pkg, null, 2) + "\n" },
    { path: "index.d.ts", content: renderDts(ifaceName, className, table) },
    { path: "index.js", content: renderJs(className, streamName) },
    {
      path: "README.md",
      content: renderReadme(table, packageName, className, streamName),
    },
  ];
}
