import type { LoggerTable } from "@/extensions/data-architect/schema";
import { firehoseS3Prefix, firehoseStreamName } from "@/lib/firehose";
import { putObject } from "@/lib/s3-client";

const SDK_BUCKET = process.env.FIREHOSE_SDK_BUCKET ?? "warehouse";
const SDK_PREFIX = process.env.FIREHOSE_SDK_PREFIX ?? "firehose-sdks/";

/** lattik-expression column types → TypeScript types for the event interface. */
function tsTypeFor(columnType: string): string {
  switch (columnType) {
    case "string":
    case "timestamp": // ISO 8601 string
    case "date": // YYYY-MM-DD string
      return "string";
    case "int32":
    case "int64":
    case "float":
    case "double":
      return "number";
    case "boolean":
      return "boolean";
    case "json":
      return "unknown";
    default:
      return "unknown";
  }
}

/**
 * Turn a logger table name like "events.click_events" into PascalCase
 * identifiers usable in TS — "EventsClickEvents".
 */
function pascalCase(name: string): string {
  return name
    .split(/[.\-_]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join("");
}

export interface GeneratedSdk {
  /** S3 key the source was written to. */
  key: string;
  /** Full S3 URI for display. */
  s3Uri: string;
  /** Bytes of the generated TS source. */
  byteLength: number;
}

/**
 * Renders a typed, self-contained TypeScript client for a Logger Table's
 * Firehose stream. The generated module exports the event interface plus a
 * small class wrapping `PutRecordBatchCommand`. Consumers install
 * `@aws-sdk/client-firehose`, drop this file into their project, and
 * `new EventsClickEventsLogger(client).send([...])`.
 */
export function renderLoggerSdkSource(table: LoggerTable): string {
  const ifaceName = `${pascalCase(table.name)}Event`;
  const className = `${pascalCase(table.name)}Logger`;
  const streamName = firehoseStreamName(table.name);
  const s3Prefix = firehoseS3Prefix(table.name);

  const fields = table.columns
    .map((c) => {
      const docLines: string[] = [];
      if (c.description) docLines.push(c.description);
      const tags = c.tags?.length ? `tags: ${c.tags.join(", ")}` : null;
      if (tags) docLines.push(tags);
      const doc =
        docLines.length > 0 ? `  /** ${docLines.join(" — ")} */\n` : "";
      return `${doc}  ${c.name}: ${tsTypeFor(c.type)};`;
    })
    .join("\n");

  return `// Generated by Lattik Studio — do not edit by hand.
// Logger Table:    ${table.name}
// Firehose Stream: ${streamName}
// S3 Output:       s3://<bucket>/${s3Prefix}
//
// Install: npm i @aws-sdk/client-firehose
//
// Usage:
//   import { FirehoseClient } from "@aws-sdk/client-firehose";
//   import { ${className} } from "./${table.name}";
//
//   const logger = new ${className}(new FirehoseClient({ region: "us-east-1" }));
//   await logger.send([{ /* typed event */ }]);

import {
  type FirehoseClient,
  PutRecordBatchCommand,
  type PutRecordBatchCommandOutput,
} from "@aws-sdk/client-firehose";

export interface ${ifaceName} {
${fields}
}

export const STREAM_NAME = ${JSON.stringify(streamName)};

export class ${className} {
  constructor(private readonly client: FirehoseClient) {}

  /**
   * Send a batch of events. Firehose accepts up to 500 records or 4 MiB per
   * call; this method does NOT chunk — callers with larger batches should
   * split first. Returns the raw SDK response so callers can inspect
   * \`FailedPutCount\` and retry partial failures.
   */
  async send(events: ${ifaceName}[]): Promise<PutRecordBatchCommandOutput> {
    const encoder = new TextEncoder();
    const records = events.map((event) => ({
      Data: encoder.encode(JSON.stringify(event) + "\\n"),
    }));
    return this.client.send(
      new PutRecordBatchCommand({
        DeliveryStreamName: STREAM_NAME,
        Records: records,
      }),
    );
  }
}
`;
}

/**
 * Generates the typed SDK module and uploads it to S3 at a deterministic
 * key derived from the table name. Returns the location for the workflow
 * card to display.
 */
export async function generateAndPublishLoggerSdk(
  table: LoggerTable,
): Promise<GeneratedSdk> {
  const source = renderLoggerSdkSource(table);
  const key = `${SDK_PREFIX}${table.name}.ts`;
  await putObject(SDK_BUCKET, key, source, "application/typescript");
  return {
    key,
    s3Uri: `s3://${SDK_BUCKET}/${key}`,
    byteLength: Buffer.byteLength(source, "utf8"),
  };
}
