import { tool, zodSchema } from "ai";
import { z } from "zod";
import {
  createBranch,
  commitFiles,
  createPullRequest,
  getGiteaPRUrl,
} from "../../../lib/gitea-client.js";
import {
  updateDefinition,
  getDefinitionByName,
} from "../lib/definitions.js";
import { getCanvasFormState } from "../lib/canvas-to-spec.js";

interface YamlFile {
  path: string;
  content: string;
}

/**
 * Names that flow into Gitea branch names, commit messages, and PR titles
 * must be tightly constrained — the value originates from canvas form state
 * which is editable by the user *and* shaped by the LLM. A prompt-injected
 * name like `../../evil` or one with embedded newlines would otherwise
 * corrupt the branch path or trick a reviewer reading the commit log.
 */
const SAFE_NAME_RE = /^[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)?$/;
const MAX_NAME_LENGTH = 60;

function isSafeDefinitionName(name: string): boolean {
  return name.length <= MAX_NAME_LENGTH && SAFE_NAME_RE.test(name);
}

/**
 * Allow only YAML files under a single top-level definitions directory and
 * reject path traversal, absolute paths, and any non-`.yaml`/`.yml`
 * extension.
 */
function isSafeYamlPath(path: string): boolean {
  if (path.length === 0 || path.length > 200) return false;
  if (path.startsWith("/") || path.startsWith("\\")) return false;
  if (path.includes("..")) return false;
  if (path.includes("\0") || path.includes("\n") || path.includes("\r")) return false;
  if (!/^[a-zA-Z0-9_./-]+$/.test(path)) return false;
  return /\.ya?ml$/i.test(path);
}

function readYamlFilesFromCanvas(canvasState: unknown): YamlFile[] | null {
  const state = getCanvasFormState(canvasState);
  const raw = state.files;
  if (!Array.isArray(raw)) return null;
  const files: YamlFile[] = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const path = (item as { path?: unknown }).path;
    const content = (item as { content?: unknown }).content;
    if (
      typeof path === "string" &&
      isSafeYamlPath(path) &&
      typeof content === "string"
    ) {
      files.push({ path, content });
    }
  }
  return files.length > 0 ? files : null;
}

const definitionKindEnum = z.enum([
  "entity",
  "dimension",
  "logger_table",
  "lattik_table",
  "metric",
]);

export interface CreateSubmitPRToolOptions {
  getCanvasState: () => unknown;
}

export function createSubmitPRTool(opts: CreateSubmitPRToolOptions) {
  return tool({
    description:
      "Submit the YAML files currently displayed in the canvas YAML editor as a PR to Gitea for review. Requires that generateYaml has been called first — reads the (possibly user-edited) YAML files directly from canvas state. The returned `prUrl` is a clickable URL that MUST be shared with the user verbatim.",
    inputSchema: zodSchema(
      z.object({
        kind: definitionKindEnum.describe(
          "The type of definition currently on the canvas",
        ),
      }),
    ),
    execute: async (input: { kind: z.infer<typeof definitionKindEnum> }) => {
      const canvasState = opts.getCanvasState();
      const state = getCanvasFormState(canvasState);
      const rawName = typeof state.name === "string" ? state.name : "";
      if (!rawName) {
        return {
          status: "error",
          message:
            "Canvas has no definition name. Run generateYaml first so the YAML editor is populated.",
        };
      }
      if (!isSafeDefinitionName(rawName)) {
        return {
          status: "error",
          message: `Definition name '${rawName}' is not safe to submit. Names must be snake_case (optionally schema.table_name) and at most ${MAX_NAME_LENGTH} characters.`,
        };
      }
      const name = rawName;
      const files = readYamlFilesFromCanvas(canvasState);
      if (!files) {
        return {
          status: "error",
          message:
            "No YAML files found on the canvas, or one or more YAML file paths failed safety checks. Run generateYaml first to populate the YAML editor before submitting a PR.",
        };
      }

      const safeBranchName = name.replace(/\./g, "_");
      const branchName = `define/${input.kind}/${safeBranchName}-${Date.now()}`;

      try {
        await createBranch(branchName);
        await commitFiles(branchName, files, `Add ${input.kind}: ${name}`);
        const pr = await createPullRequest(
          `Define ${input.kind}: ${name}`,
          `## Definition\n\n**Kind:** ${input.kind}\n**Name:** ${name}\n\nGenerated by Lattik Studio Data Architect.`,
          branchName,
        );
        const prUrl = getGiteaPRUrl(pr.number);

        const def = await getDefinitionByName(input.kind, name);
        if (def) {
          await updateDefinition(def.id, {
            status: "pending_review",
            prUrl,
          });
        }

        const filePaths = files.map((f) => f.path);
        // Phase 2 will replace this with a render-intent. For now we emit the
        // same json-render Spec shape apps/web's chat watcher already
        // understands — typed as `unknown` to keep @json-render/core out of
        // agent-service.
        const spec: unknown = {
          root: "main",
          elements: {
            main: {
              type: "PRSubmittedCard",
              props: {
                kind: input.kind,
                name,
                prNumber: pr.number,
                prUrl,
                branch: branchName,
                files: filePaths,
              },
              children: [],
            },
          },
          state: {},
        };

        return {
          status: "submitted",
          prNumber: pr.number,
          prUrl,
          branch: branchName,
          files: filePaths,
          spec,
        };
      } catch (error) {
        console.error("submitPR error:", error);
        const detail = error instanceof Error ? error.message : String(error);
        return {
          status: "error",
          message: `Failed to submit PR: ${detail}`,
        };
      }
    },
  });
}
